#! /bin/sh

# Installation
# - Create symlink /etc/init.d/openhouse to this file
# - chmod +x the symlink

NAME=openhouse
DESC="OpenHouse Daemon"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="/var/log/${NAME}.log"

DAEMON="/usr/bin/php-cli"
DAEMON_DIR="/etc/openhouse"
DAEMON_FILE="${DAEMON_DIR}/main.php"

START_OPTS="-S -b -m -p ${PIDFILE} -x ${DAEMON} ${DAEMON_FILE}"
STOP_OPTS="-K -p ${PIDFILE}"

test -x $DAEMON || exit 0

set -e

case "$1" in
    start)
        echo -n "Starting ${DESC}: "
        cd $DAEMON_DIR
        start-stop-daemon $START_OPTS >> $LOGFILE
        echo "$NAME."
        ;;
    stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon $STOP_OPTS
        echo "$NAME."
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        echo -n "Restarting $DESC: "
        stop
        sleep 1
        start
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0