#! /bin/sh /etc/rc.common

START=98
STOP=10

NAME=openhouse
DESC="OpenHouse Daemon"
PIDFILE="/var/run/${NAME}"
CONFFILE="/etc/openhouse.json"

DAEMON_CLI="/usr/bin/php-cli"
DAEMON_DIR="/etc/openhouse"
DAEMON_FILE="main.php"
DAEMON_OPTS="${CONFFILE}"

START_OPTS="-S -b -m -p ${PIDFILE} -x ${DAEMON_CLI} ${DAEMON_FILE} ${DAEMON_OPTS}"
STOP_OPTS="-K -p ${PIDFILE}"

reload() {
    stop
}

start() {
    echo -n "Starting ${DESC}"
    cd $DAEMON_DIR
    start-stop-daemon $START_OPTS
    return 0
}

stop() {
    echo -n "Stopping ${DESC}"
    start-stop-daemon $STOP_OPTS
    rm -f $PIDFILE
    return 0
}

restart() {
    echo -n "Restarting ${DESC}"
    stop
    sleep 1
    start
}