#! /bin/sh

# Installation
# - Create symlink /etc/init.d/openhouse to this file
# - chmod +x the symlink

NAME=openhouse
DESC="OpenHouse Daemon"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="/var/log/${NAME}.log"
CONFFILE="/etc/openhouse.json"

DAEMON_CLI="/usr/bin/php-cli"
DAEMON_DIR="/etc/openhouse"
DAEMON_FILE="main.php"
DAEMON_OPTS="${CONFFILE}"

START_OPTS="-S -b -m -p ${PIDFILE} -x ${DAEMON_CLI} ${DAEMON_FILE} ${DAEMON_OPTS}"
STOP_OPTS="-K -p ${PIDFILE}"

test -x $DAEMON_CLI || exit 0

set -e

start() {
    echo -n "Starting ${DESC}"
    cd $DAEMON_DIR
    start-stop-daemon $START_OPTS >> $LOGFILE
    return 0
}

stop() {
    echo -n "Stopping ${DESC}"
    start-stop-daemon $STOP_OPTS
    rm -f $PIDFILE
    return 0
}

restart() {
    echo -n "Restarting ${DESC}"
    stop
    sleep 1
    start
}

usage() {
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        restart
        ;;
    *)
        usage
        ;;
esac

exit 0